version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "docker_db"
      MYSQL_USER: "docker_usr"
      MYSQL_PASSWORD: "docker_pwd"
    restart: unless-stopped